server:
  port: 5555

spring:
  ai:
    openai:
      # 替换为自己的硅基流动API密钥，否则启动报错
      api-key: sk-vwwaanivkoynibhcvsfrtlxzuogkrqwuxrxrvpajvwtgchbp
      base-url: https://api.siliconflow.cn/
      embedding:
        options:
          model: BAAI/bge-m3
      chat:
        options:
          model: deepseek-ai/DeepSeek-V3
  data:
    mongodb:
      uri: mongodb://localhost:27017/ai_chat_demo